spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://postgres:5432/hotel_reservation
    username: hotel_user
    password: hotel_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  security:
    user:
      name: admin
      password: admin123

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  
  instance:
    hostname: user-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

jwt:
  secret: hotelReservationSystemSecretKey2024ForDevelopmentOnly
  expiration: 86400

logging:
  level:
    com.hotelreservation.user: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 